In [1]:
#imports
import pandas as pd
%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
import calendar
import folium
from folium import plugins
from folium.plugins import HeatMap

In [2]:
# Consignpro's user guide defining some columns
# https://www.consignpro.com/download/UserGuide.pdf

In [3]:
df_customers = pd.read_excel('Customers.xlsx', index_col="CustomerID")

In [4]:
df_customers.head()

First Name    Last Name                Address           City  \
CustomerID                                                                 
0              filler       filler                 filler         filler   
1                 K&N  Consignment        3704 N. Western  Oklahoma City   
2                Alan      Soltani  1503 Winding Ridge Rd         Edmond   
3               Sarah        Brock       8309 NW 146th St  Oklahoma City   
4             Beverly       Witman        3802 US HWY 377            Ada   

           State  Postal Code  Work Phone    Home Phone  AccountBalance  \
CustomerID                                                                
0            NaN          NaN         NaN           NaN            0.00   
1             OK      73118.0         NaN  4.055210e+09          118.24   
2             OK      73034.0       405.0  4.059190e+09            0.00   
3             OK      73142.0         NaN  8.704895e+09            5.00   
4             OK      74820.0         NaN  5.802793e+09            1.88   

           OpenedDate  ...                             CustNotes  \
CustomerID             ...                                         
0            1/1/1990  ...                                   NaN   
1           9/18/2015  ...                                 Store   
2           9/18/2015  ...              Owes $50 p/u 9-17-15 njl   
3           9/22/2015  ...               $50 p/u  pd 11-2-15 NJL   
4           9/23/2015  ...  Pick Up Fee Of $50.00 pd 11-2-15 NJL   

                                        Email  CheckAmt  PickupDate  \
CustomerID                                                            
0                                         NaN       0.0         NaT   
1             kninteriorconsignment@gmail.com       0.0  2015-07-20   
2              asoltani@olssonassociation.com       0.0  2015-12-17   
3           sarahkatherinejohnson12@gmail.com       0.0  2015-12-21   
4                         bookbev@outlook.com       0.0  2015-12-22   

            BirthMonth  PickupDate2  PickupDate3  UseMRW  TotalSales  Locked  
CustomerID                                                                    
0                  NaN          NaT          NaT   False      61.200   False  
1                  NaN   2016-06-05   2019-04-26   False  768531.800   False  
2                  NaN          NaT          NaT   False     249.500   False  
3                  NaN          NaT          NaT   False    1501.191   False  
4                  NaN          NaT          NaT   False    9924.199   False  

[5 rows x 31 columns]

In [5]:
df_activity = pd.read_excel('Activity.xlsx', index_col="ID")

In [6]:
df_activity.head()

CustomerID PostingDate PostingTime  TrxAmount TrxCode Salesperson  \
ID                                                                         
16082          20  2017-09-01    16:58:47   0.000004       O      System   
16105           4  2018-05-23    16:11:45   1.879968       O      System   
16106           6  2015-11-03    18:31:15   0.000000       O      System   
16107          38  2018-04-01    15:50:25   0.000008       O      System   
16108          26  2016-09-01    17:58:53   0.000000       O      System   

       ProductID  DraftNumber  Date1  Text1  Num1 Message  ClearedDate  
ID                                                                      
16082          0            0    NaN    NaN     0     NaN          NaN  
16105          0            0    NaN    NaN     0     NaN          NaN  
16106          0            0    NaN    NaN     0     NaN          NaN  
16107          0            0    NaN    NaN     0     NaN          NaN  
16108          0            0    NaN    NaN     0     NaN          NaN

In [7]:
df_invoices = pd.read_excel('Invoices.xlsx', index_col="Invoice ID")

In [8]:
df_invoices.head()

Employee Invoice Date PaymentTerms  GrossDue  Discount  \
Invoice ID                                                              
0                    cp    12/1/2005          NaN       0.0       0.0   
2439                NaN          NaN          NaN       0.0       0.0   
2964                NaN          NaN          NaN       0.0       0.0   
6457                NaN          NaN          NaN       0.0       0.0   
8112        Voided-Noel    8/13/2018       Refund    -605.0       0.0   

            SalesTax  AcctCredit  NetDue  ItemCount  CreditCardCut  ...  \
Invoice ID                                                          ...   
0               0.00           0    0.00          0              0  ...   
2439            0.00           0    0.00          0              0  ...   
2964            0.00           0    0.00          0              0  ...   
6457            0.00           0    0.00          0              0  ...   
8112          -50.67           0 -655.67          1              0  ...   

            BuyersFee  Layaways  TaxExemptNo LayCredit  RegisterID Advertise  \
Invoice ID                                                                     
0                 NaN       NaN          NaN       NaN         1.0       NaN   
2439              NaN       NaN          NaN       NaN         NaN       NaN   
2964              NaN       NaN          NaN       NaN         NaN       NaN   
6457              NaN       NaN          NaN       NaN         NaN       NaN   
8112              NaN       0.0          NaN       0.0         1.0      8073   

            ConsID  GCSales  GCCredits  CustNo  
Invoice ID                                      
0              NaN      NaN        NaN     NaN  
2439           NaN      NaN        NaN     NaN  
2964           NaN      NaN        NaN     NaN  
6457           NaN      NaN        NaN     NaN  
8112           NaN      0.0        0.0     NaN  

[5 rows x 28 columns]

In [9]:
df_inv_det = pd.read_excel('InvDetails.xlsx', index_col="Invoice Detail ID")

In [10]:
df_inv_det.head()

Invoice ID  Product ID  Price Per Unit  TaxAmount  \
Invoice Detail ID                                                      
0                           0           0             0.0        NaN   
16226                    8113       19708            19.8       1.66   
16227                    8113       20519            22.0       1.84   
16228                    8114       20246           247.0      20.69   
16229                    8116       20049             9.9       0.83   

                   ConsignorID  StoreOwned  ItemCost  FedTax  Voided  TaxRef  \
Invoice Detail ID                                                              
0                          NaN       False       NaN     NaN   False     NaN   
16226                   1362.0       False      9.01     0.0   False     NaN   
16227                      1.0        True      0.00     0.0   False     NaN   
16228                   1382.0       False    112.40     0.0   False     NaN   
16229                   1292.0       False      4.51     0.0   False     NaN   

                   FedTaxRef  DiscRef  CardNumber VoidBy  
Invoice Detail ID                                         
0                        NaN      NaN         NaN    NaN  
16226                    NaN      NaN         NaN    NaN  
16227                    NaN      NaN         NaN    NaN  
16228                    NaN      NaN         NaN    NaN  
16229                    NaN      NaN         NaN    NaN

In [11]:
df_employees = pd.read_excel('Employees.xlsx', index_col="Employee ID")

In [12]:
df_employees.head(1)

Password  AdminPrivledge  Social Security Number FirstName  \
Employee ID                                                              
1              noel1            True             999999999.0      Noel   

            Last Name  Title         Address           City State  \
Employee ID                                                         
1                Ladd    NaN  3704 N Western  Oklahoma City    OK   

             Postal Code  ...  StoreID AdminFin AdminVoid  AdminCons  \
Employee ID               ...                                          
1                  73118  ...        1     True      True       True   

             AdminInv  AdminEmp  AdminAct  AdminBal  MakeSale  NotMakeSale  
Employee ID                                                                 
1                True      True      True      True     False        False  

[1 rows x 24 columns]

In [13]:
df_pay_totals = pd.read_excel('PayTotals.xlsx')

In [14]:
df_pay_totals.head()

PayDate     PayTerms  PayTotal  PayCount
0 2015-09-24        Check     42.27         1
1 2015-09-24  Credit Card    243.84         1
2 2015-09-25  Credit Card      8.67         1
3 2015-09-26        Check    486.60         1
4 2015-09-26  Credit Card   1919.32         3

In [15]:
df_merchandise = pd.read_excel('Merchandise.xlsx', index_col="ProductID")

In [16]:
df_merchandise.head()

ProductType ProductColor ProductSize        ProductDescription  \
ProductID                                                                  
-2               None         None        None                      Lamp   
-1               None         None        None  Wrought Iron W. 5 Chairs   
 0             filler       filler      filler                    filler   
 1               None         None        None             Candle Holder   
 2               None         None        None                     Colum   

           OrigPrice   Price  EnterDate TransferDate  TransferPrice  \
ProductID                                                             
-2            147.60  147.60 2018-08-18   2018-08-18         147.60   
-1            124.75  124.75 2018-07-03   2018-07-03         124.75   
 0               NaN    0.00 1999-12-31   2018-04-14          68.00   
 1              2.00    2.00 2020-05-20   2020-05-20           2.00   
 2             49.50   49.50 2020-07-18   2020-07-18          49.50   

          TransferInd  ... ListOnline  CustNo  FixSplit  TaxRate  PhyDate  \
ProductID              ...                                                  
-2               Sold  ...      False     NaN     False      NaN      NaN   
-1               Sold  ...      False     NaN     False      NaN      NaN   
 0               Sold  ...      False     NaN     False      NaN      NaN   
 1               Sold  ...      False     NaN     False      NaN      NaN   
 2               Sold  ...      False     NaN     False      NaN      NaN   

          Auction2 ConCode BuyOut  CardFee  Reminded  
ProductID                                             
-2             NaN     NaN  False      0.0     False  
-1             NaN     NaN  False      0.0     False  
 0             NaN     NaN  False      0.0     False  
 1             NaN     NaN  False      0.0     False  
 2             NaN     NaN  False      0.0     False  

[5 rows x 50 columns]

In [17]:
df_user_lists = pd.read_excel('UserLists.xlsx', index_col="ID")

In [18]:
df_user_lists.head()

ListNumber         Value  ChargePercent  SplitPct  ConPeriod  Markdown  \
ID                                                                           
75           0          Desk              0       NaN        NaN       NaN   
76           0          Sofa              0       NaN        NaN       NaN   
77           0  Dining Table              0       NaN        NaN       NaN   
78           0    Side Table              0       NaN        NaN       NaN   
79           0  Coffee Table              0       NaN        NaN       NaN   

    MDDay1  MDPct1  MDDay2  MDPct2  ...  NoTax  SmartP  LowP  HighP  TiedTwo  \
ID                                  ...                                        
75     NaN     NaN     NaN     NaN  ...  False     NaN   NaN    NaN      NaN   
76     NaN     NaN     NaN     NaN  ...  False     NaN   NaN    NaN      NaN   
77     NaN     NaN     NaN     NaN  ...  False     NaN   NaN    NaN      NaN   
78     NaN     NaN     NaN     NaN  ...  False     NaN   NaN    NaN      NaN   
79     NaN     NaN     NaN     NaN  ...  False     NaN   NaN    NaN      NaN   

    TaxRate  TotSales  NumSales  Reduce  TaxExceed  
ID                                                  
75      NaN  41680.42     132.0     NaN        NaN  
76      NaN  70513.86     169.0     NaN        NaN  
77      NaN  22310.27      42.0     NaN        NaN  
78      NaN   9730.69      70.0     NaN        NaN  
79      NaN  23344.40     113.0     NaN        NaN  

[5 rows x 22 columns]

## Customers Dataset Cleaning

In [19]:
df_customers.shape

(2272, 31)

In [20]:
df_customers.count()

First Name        2272
Last Name         2272
Address           2272
City              2272
State             2271
Postal Code       2271
Work Phone         915
Home Phone        2243
AccountBalance    2272
OpenedDate        2272
ActivityDate      2272
StoreID           2272
ActiveInd         2272
CheckFee          2272
Date1                0
Text1                0
Num1              2272
ConsignCode          0
Street2            151
Return            2272
ActiveItems        465
CustNotes         2243
Email             2193
CheckAmt          2039
PickupDate         708
BirthMonth           2
PickupDate2        171
PickupDate3         73
UseMRW            2272
TotalSales        2272
Locked            2272
dtype: int64

In [21]:
df_customers.dtypes

First Name                object
Last Name                 object
Address                   object
City                      object
State                     object
Postal Code              float64
Work Phone               float64
Home Phone               float64
AccountBalance           float64
OpenedDate                object
ActivityDate              object
StoreID                    int64
ActiveInd                   bool
CheckFee                   int64
Date1                    float64
Text1                    float64
Num1                       int64
ConsignCode              float64
Street2                   object
Return                      bool
ActiveItems              float64
CustNotes                 object
Email                     object
CheckAmt                 float64
PickupDate        datetime64[ns]
BirthMonth               float64
PickupDate2       datetime64[ns]
PickupDate3       datetime64[ns]
UseMRW                      bool
TotalSales               float64
Locked    

In [22]:
df_customers['StoreID'].unique()
# will drop from dataframe

array([1])

In [23]:
df_customers['ActiveInd'].unique()

array([False,  True])

In [24]:
df_customers['CheckFee'].unique()
# will drop

array([   0, 9999])

In [25]:
df_customers['Num1'].unique()
# will drop

array([ 0, 50])

In [26]:
df_customers['Street2'].unique()

array([nan, 'Unit 3', '#141', 'STE 18-137', 'Apt 2607', '#2209', '#418',
       'Edmond', 'Ste. 505', '#1', 'A204', '#118', '#6311', '#103',
       'Apt K', 'Apt. 924', 'Apt. C', 'Apt. A', 'Villa 82', 'Apt. 1138',
       'Apt #1138', 'Apt 425', 'Apt 204', 'Apt 104', 'Unit 61', '207B',
       '#A120', '#112', '#2222', '#G', '#18201', 'Apt. 452', 'Apt 8210',
       'Apt. 14k1', 'Apt 2320', 'Apt. 612', 'Oak Hollow Rd', 'Apt. 132',
       '#24101', '#909', 'Unit 101', '#803', '#340', 'Ste. 200',
       'Apt 248', '#9', 'Apt. 17D', 'Apt 16108', 'Apt 1005', 'Apt 1512',
       '#225A', 'Unit #185', '#22', '#309', 'Apt # 1702', '9-137',
       'Suite #1550', 'Apt 1428', 'Suite 1403', 'Villa 80', 'Apt #4',
       'Apt 418', 'Dale St', '#2117', 'Apt. 19208', '910 S. Main',
       '#2705', 'Suite 112', '#276', 'Unit 150', 'Apt # 155', '#14',
       '#465', 'Apt 5108', 'Apt 222', '#233', 'Villa 27', 'Apt 134',
       'Suite 200', '#169', 'Unit B', '#201', 'Suite 3121', 'Apt 202',
       '#31', 'AP

In [27]:
df_customers['ActiveItems'].unique()

array([ 0., 44.,  1., 14.,  3.,  2.,  7.,  4., 19.,  6., 76., 11., 57.,
        5., 94., 16.,  8., 17., 12.,  9., 25., 41., nan])

In [28]:
df_customers['CustNotes'].unique()

array([nan, 'Store', 'Owes $50 p/u 9-17-15 njl', ...,
       'PU $75 GG 8/12/2020', 'Brought in 8/12/2020 GG', 'Brout in'],
      dtype=object)

In [29]:
df_customers['CheckAmt'].unique()
# will drop

array([ 0., nan])

In [30]:
df_customers['Locked'].unique()
# will drop

array([False])

In [31]:
# deleting columns that will not be relevant to this analysis
df_customers = df_customers.drop(['Work Phone','Home Phone','Date1', 'Text1','ConsignCode','BirthMonth','StoreID','CheckFee',
                                  'Num1','Email','ActiveInd','Return','CustNotes','CheckAmt','UseMRW','Locked'], axis=1)
df_customers.head()

First Name    Last Name                Address           City  \
CustomerID                                                                 
0              filler       filler                 filler         filler   
1                 K&N  Consignment        3704 N. Western  Oklahoma City   
2                Alan      Soltani  1503 Winding Ridge Rd         Edmond   
3               Sarah        Brock       8309 NW 146th St  Oklahoma City   
4             Beverly       Witman        3802 US HWY 377            Ada   

           State  Postal Code  AccountBalance OpenedDate ActivityDate Street2  \
CustomerID                                                                      
0            NaN          NaN            0.00   1/1/1990    5/18/2018     NaN   
1             OK      73118.0          118.24  9/18/2015    8/12/2020     NaN   
2             OK      73034.0            0.00  9/18/2015     4/5/2016     NaN   
3             OK      73142.0            5.00  9/22/2015     7/2/2017     NaN   
4             OK      74820.0            1.88  9/23/2015    5/22/2018     NaN   

            ActiveItems PickupDate PickupDate2 PickupDate3  TotalSales  
CustomerID                                                              
0                   0.0        NaT         NaT         NaT      61.200  
1                   0.0 2015-07-20  2016-06-05  2019-04-26  768531.800  
2                   0.0 2015-12-17         NaT         NaT     249.500  
3                   0.0 2015-12-21         NaT         NaT    1501.191  
4                   0.0 2015-12-22         NaT         NaT    9924.199

In [32]:
# drop the first two rows which are just a filler row and the store's info
df_customers = df_customers.drop([0,1])
df_customers.head()

First Name Last Name                Address           City State  \
CustomerID                                                                    
2                Alan   Soltani  1503 Winding Ridge Rd         Edmond    OK   
3               Sarah     Brock       8309 NW 146th St  Oklahoma City    OK   
4             Beverly    Witman        3802 US HWY 377            Ada    OK   
5               Juana      Hall       702 Wakefield Rd          Perry    OK   
6              Warren     Field       3221 Orchard Ave         Edmond    OK   

            Postal Code  AccountBalance OpenedDate ActivityDate Street2  \
CustomerID                                                                
2               73034.0            0.00  9/18/2015     4/5/2016     NaN   
3               73142.0            5.00  9/22/2015     7/2/2017     NaN   
4               74820.0            1.88  9/23/2015    5/22/2018     NaN   
5               73077.0            0.00  9/23/2015    6/29/2020     NaN   
6               73012.0            0.00  9/23/2015   11/12/2015     NaN   

            ActiveItems PickupDate PickupDate2 PickupDate3  TotalSales  
CustomerID                                                              
2                   0.0 2015-12-17         NaT         NaT     249.500  
3                   0.0 2015-12-21         NaT         NaT    1501.191  
4                   0.0 2015-12-22         NaT         NaT    9924.199  
5                   0.0        NaT         NaT         NaT    1533.500  
6                   0.0        NaT         NaT         NaT    1048.000

In [33]:
# change 'Postal Code' from a float to a string
df_customers['Postal Code'] = df_customers['Postal Code'].astype(str).str[:-2]
df_customers.head()

First Name Last Name                Address           City State  \
CustomerID                                                                    
2                Alan   Soltani  1503 Winding Ridge Rd         Edmond    OK   
3               Sarah     Brock       8309 NW 146th St  Oklahoma City    OK   
4             Beverly    Witman        3802 US HWY 377            Ada    OK   
5               Juana      Hall       702 Wakefield Rd          Perry    OK   
6              Warren     Field       3221 Orchard Ave         Edmond    OK   

           Postal Code  AccountBalance OpenedDate ActivityDate Street2  \
CustomerID                                                               
2                73034            0.00  9/18/2015     4/5/2016     NaN   
3                73142            5.00  9/22/2015     7/2/2017     NaN   
4                74820            1.88  9/23/2015    5/22/2018     NaN   
5                73077            0.00  9/23/2015    6/29/2020     NaN   
6                73012            0.00  9/23/2015   11/12/2015     NaN   

            ActiveItems PickupDate PickupDate2 PickupDate3  TotalSales  
CustomerID                                                              
2                   0.0 2015-12-17         NaT         NaT     249.500  
3                   0.0 2015-12-21         NaT         NaT    1501.191  
4                   0.0 2015-12-22         NaT         NaT    9924.199  
5                   0.0        NaT         NaT         NaT    1533.500  
6                   0.0        NaT         NaT         NaT    1048.000

In [34]:
# check that column is of dtype Object ('O')
df_customers['Postal Code'].dtypes

dtype('O')

In [35]:
df_customers.tail()

First Name   Last Name             Address           City  \
CustomerID                                                                   
2271                  James       Cowiz       763 Mohawk St       Columbus   
2272        Staci And Brian    Campbell      1201 Irvine Dr         Edmond   
2273                  Louis       Green        200 N Harvey  Oklahoma City   
2274                  Carol  Goetzinger  1729 Coventry Lane  Oklahoma City   
2275                   Gary    Thompson     10407 N May Ave  Oklahoma City   

           State Postal Code  AccountBalance OpenedDate ActivityDate Street2  \
CustomerID                                                                     
2271          OH       43206             0.0  8/11/2020    8/11/2020     NaN   
2272          OK       73025             0.0  8/11/2020    8/12/2020     NaN   
2273          OK       73102           -75.0  8/12/2020    8/12/2020     606   
2274          00       73120             0.0  8/12/2020    8/12/2020     NaN   
2275          OK       73120             0.0  8/12/2020    8/12/2020     NaN   

            ActiveItems PickupDate PickupDate2 PickupDate3  TotalSales  
CustomerID                                                              
2271                NaN 2020-11-09         NaT         NaT         0.0  
2272                NaN 2020-11-09         NaT         NaT         0.0  
2273                NaN        NaT         NaT         NaT         0.0  
2274                NaN 2020-11-10         NaT         NaT         0.0  
2275                NaN 2020-11-10         NaT         NaT         0.0

In [36]:
df_customers.shape

(2270, 15)

## Activity Dataset Cleaning

In [37]:
df_activity.head()

CustomerID PostingDate PostingTime  TrxAmount TrxCode Salesperson  \
ID                                                                         
16082          20  2017-09-01    16:58:47   0.000004       O      System   
16105           4  2018-05-23    16:11:45   1.879968       O      System   
16106           6  2015-11-03    18:31:15   0.000000       O      System   
16107          38  2018-04-01    15:50:25   0.000008       O      System   
16108          26  2016-09-01    17:58:53   0.000000       O      System   

       ProductID  DraftNumber  Date1  Text1  Num1 Message  ClearedDate  
ID                                                                      
16082          0            0    NaN    NaN     0     NaN          NaN  
16105          0            0    NaN    NaN     0     NaN          NaN  
16106          0            0    NaN    NaN     0     NaN          NaN  
16107          0            0    NaN    NaN     0     NaN          NaN  
16108          0            0    NaN    NaN     0     NaN          NaN

In [38]:
df_activity.dtypes

CustomerID              int64
PostingDate    datetime64[ns]
PostingTime            object
TrxAmount             float64
TrxCode                object
Salesperson            object
ProductID               int64
DraftNumber             int64
Date1                 float64
Text1                 float64
Num1                    int64
Message                object
ClearedDate           float64
dtype: object

In [39]:
df_activity['PostingTime'] =  pd.to_datetime(df_activity['PostingTime'], format='%H:%M:%S').dt.time
df_activity.head()

CustomerID PostingDate PostingTime  TrxAmount TrxCode Salesperson  \
ID                                                                         
16082          20  2017-09-01    16:58:47   0.000004       O      System   
16105           4  2018-05-23    16:11:45   1.879968       O      System   
16106           6  2015-11-03    18:31:15   0.000000       O      System   
16107          38  2018-04-01    15:50:25   0.000008       O      System   
16108          26  2016-09-01    17:58:53   0.000000       O      System   

       ProductID  DraftNumber  Date1  Text1  Num1 Message  ClearedDate  
ID                                                                      
16082          0            0    NaN    NaN     0     NaN          NaN  
16105          0            0    NaN    NaN     0     NaN          NaN  
16106          0            0    NaN    NaN     0     NaN          NaN  
16107          0            0    NaN    NaN     0     NaN          NaN  
16108          0            0    NaN    NaN     0     NaN          NaN

In [40]:
df_activity.dtypes

CustomerID              int64
PostingDate    datetime64[ns]
PostingTime            object
TrxAmount             float64
TrxCode                object
Salesperson            object
ProductID               int64
DraftNumber             int64
Date1                 float64
Text1                 float64
Num1                    int64
Message                object
ClearedDate           float64
dtype: object