In [1]:
#imports
import pandas as pd
%matplotlib inline 
import matplotlib.pyplot as plt
from matplotlib import dates as mpl_dates
from matplotlib.pyplot import figure
import numpy as np
import seaborn as sns
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
import calendar

In [2]:
df_merchandise = pd.read_excel('Merchandise.xlsx', index_col="ProductID")

## Data Preprocessing & Analysis

In [3]:
df_merchandise.head()

ProductType ProductColor ProductSize        ProductDescription  \
ProductID                                                                  
-2               None         None        None                      Lamp   
-1               None         None        None  Wrought Iron W. 5 Chairs   
 0             filler       filler      filler                    filler   
 1               None         None        None             Candle Holder   
 2               None         None        None                     Colum   

           OrigPrice   Price  EnterDate TransferDate  TransferPrice  \
ProductID                                                             
-2            147.60  147.60 2018-08-18   2018-08-18         147.60   
-1            124.75  124.75 2018-07-03   2018-07-03         124.75   
 0               NaN    0.00 1999-12-31   2018-04-14          68.00   
 1              2.00    2.00 2020-05-20   2020-05-20           2.00   
 2             49.50   49.50 2020-07-18   2020-07-18          49.50   

          TransferInd  ... ListOnline  CustNo  FixSplit  TaxRate  PhyDate  \
ProductID              ...                                                  
-2               Sold  ...      False     NaN     False      NaN      NaN   
-1               Sold  ...      False     NaN     False      NaN      NaN   
 0               Sold  ...      False     NaN     False      NaN      NaN   
 1               Sold  ...      False     NaN     False      NaN      NaN   
 2               Sold  ...      False     NaN     False      NaN      NaN   

          Auction2 ConCode BuyOut  CardFee  Reminded  
ProductID                                             
-2             NaN     NaN  False      0.0     False  
-1             NaN     NaN  False      0.0     False  
 0             NaN     NaN  False      0.0     False  
 1             NaN     NaN  False      0.0     False  
 2             NaN     NaN  False      0.0     False  

[5 rows x 50 columns]

In [4]:
df_merchandise.shape

(15308, 50)

In [5]:
df_merchandise.count()

ProductType           15308
ProductColor          15308
ProductSize           15308
ProductDescription    15308
OrigPrice             15307
Price                 15308
EnterDate             15308
TransferDate          10923
TransferPrice         15308
TransferInd           15308
TransferBy            15308
CustomerID            15308
ReqPrice              15308
InvoiceNumber         10906
Return                15308
MarkdownDate1          9976
MarkdownDate2          8497
MarkdownDate3          6976
LabelPrinted          15308
MercCut               15307
DownPymt              15308
DownWho                   0
DownDate                  0
ItemCount             15308
Date1                     0
Text1                   395
Num1                  15308
ExpireDate            15308
LayawayGrp                0
PCName                14925
DontPrintTag          15308
ItemNotes                 0
WholesalePrice        15308
BuyersFee             15308
DownPhone                 0
ResaleNow           

In [6]:
df_merchandise['DownPymt'].unique()
# will drop

array([0])

In [7]:
df_merchandise['Num1'].unique()
# will drop

array([0])

In [8]:
df_merchandise['Taxable'].unique()

array([nan, 'Y', 'N'], dtype=object)

In [9]:
df_merchandise['Taxable'].value_counts()
# will drop

Y    14910
N       15
Name: Taxable, dtype: int64

In [10]:
df_merchandise['NeverMD'].unique()

array([nan, 'Y', 'N'], dtype=object)

In [11]:
df_merchandise['NeverMD'].value_counts()
# will drop, unable to find documentation for this column description

N    13159
Y     1766
Name: NeverMD, dtype: int64

In [12]:
df_merchandise['TaxRate'].unique()
# will drop, these values will be worthless

array([nan,  0.])

In [13]:
df_merchandise['CardFee'].unique()
# will drop, these values will be worthless

array([ 0., nan])

In [14]:
# drop columns with no/many missing values and ones that are unnecessary
df_merchandise = df_merchandise.drop(['DownWho','DownDate','Date1','Text1','LayawayGrp','ItemNotes','Num1',
                                      'DownPhone','PreviousOwner','LabelPrinted','PCName','DontPrintTag',
                                      'Taxable','WholesalePrice','AuctionID','CustNo','PhyDate','Auction2',
                                      'DownPymt','ResaleNow','ListOnline','FixSplit','ConCode','NeverMD',
                                      'BuyOut','TaxRate','Reminded','CardFee'], axis=1)

In [15]:
# drop filler row
df_merchandise = df_merchandise.drop([0])
df_merchandise.head()

ProductType ProductColor ProductSize        ProductDescription  \
ProductID                                                                  
-2               None         None        None                      Lamp   
-1               None         None        None  Wrought Iron W. 5 Chairs   
 1               None         None        None             Candle Holder   
 2               None         None        None                     Colum   
 3               None         None        None             Credenza Lamp   

           OrigPrice   Price  EnterDate TransferDate  TransferPrice  \
ProductID                                                             
-2            147.60  147.60 2018-08-18   2018-08-18         147.60   
-1            124.75  124.75 2018-07-03   2018-07-03         124.75   
 1              2.00    2.00 2020-05-20   2020-05-20           2.00   
 2             49.50   49.50 2020-07-18   2020-07-18          49.50   
 3             71.10   71.10 2018-08-25   2018-08-25          71.10   

          TransferInd  ... ReqPrice  InvoiceNumber  Return  MarkdownDate1  \
ProductID              ...                                                  
-2               Sold  ...      0.0         8150.0   False            NaT   
-1               Sold  ...      0.0         7749.0   False            NaT   
 1               Sold  ...      0.0        13211.0   False            NaT   
 2               Sold  ...      0.0        13842.0   False            NaT   
 3               Sold  ...      0.0         8225.0   False            NaT   

           MarkdownDate2 MarkdownDate3 MercCut ItemCount  ExpireDate  \
ProductID                                                              
-2                   NaT           NaT     0.0         0  2018-11-16   
-1                   NaT           NaT     0.5         0  2018-10-01   
 1                   NaT           NaT     0.0         0  2020-08-18   
 2                   NaT           NaT     0.5         0  2020-10-16   
 3                   NaT           NaT     0.0         0  2018-11-23   

           BuyersFee  
ProductID             
-2               0.0  
-1               0.0  
 1               0.0  
 2               0.0  
 3               0.0  

[5 rows x 22 columns]

In [16]:
df_merchandise.dtypes

ProductType                   object
ProductColor                  object
ProductSize                   object
ProductDescription            object
OrigPrice                    float64
Price                        float64
EnterDate             datetime64[ns]
TransferDate          datetime64[ns]
TransferPrice                float64
TransferInd                   object
TransferBy                    object
CustomerID                     int64
ReqPrice                     float64
InvoiceNumber                float64
Return                          bool
MarkdownDate1         datetime64[ns]
MarkdownDate2         datetime64[ns]
MarkdownDate3         datetime64[ns]
MercCut                      float64
ItemCount                      int64
ExpireDate            datetime64[ns]
BuyersFee                    float64
dtype: object

In [17]:
# MercCut signifies 0.5 for items consigned (50/50 split), 0.0 for items the store purchased new
df_merchandise.MercCut.value_counts()

# 13,255 of the items have been consigned

0.5    13255
0.0     2052
Name: MercCut, dtype: int64

In [18]:
# Convert invoice number to int from float
df_merchandise.InvoiceNumber = df_merchandise.InvoiceNumber.fillna(0.0).astype(int)
df_merchandise.InvoiceNumber.dtype

dtype('int64')

In [19]:
df_merchandise.shape

(15307, 22)

In [20]:
# View top 21 selling items and their value counts
df_merchandise['ProductType'].value_counts().head(21)

Accessory       5266
Chair           1194
Decor            655
Table            402
None             384
Pillow           371
Art              365
Sofa             296
Rug              293
End Table        228
Lamp             224
Picture          221
Desk             171
Light            155
Bed              140
Barstool         124
Mirror           113
Coffee Table     111
Chest            104
Dining Table     104
Console           99
Name: ProductType, dtype: int64

In [21]:
products = df_merchandise['ProductType'].value_counts()
products[products < 10].shape
# there are 1103 different entry labels for the Product Type column that occur 10 or less times 
# I will likely exclude these entries from the dataframe when analyzing products since cleaning 1000+ rows is
# not feasible given the timeline of this project

(1103,)

In [22]:
products[products < 100].shape
# Outside of the top 20 selling items listed in ProductType (#20 having 104 entries), there are 1191 different 
# entry labels for this category. Only the top 20 items for this category will be analyzed

(1191,)

In [23]:
# Filter datframe for top 20 selling items from Product Type
top20_items = df_merchandise[df_merchandise.groupby('ProductType')['ProductType'].transform('size') > 100]
top20_items.ProductType.value_counts()

Accessory       5266
Chair           1194
Decor            655
Table            402
None             384
Pillow           371
Art              365
Sofa             296
Rug              293
End Table        228
Lamp             224
Picture          221
Desk             171
Light            155
Bed              140
Barstool         124
Mirror           113
Coffee Table     111
Chest            104
Dining Table     104
Name: ProductType, dtype: int64

In [24]:
df_merchandise[df_merchandise.groupby('ProductType')['ProductType'].transform('size') < 100].shape
# 4,386 rows will be excluded from top20 item analysis

(4386, 22)

In [25]:
top20_items.shape
# Filtering by the top 20 items for Product Type changed our dataframe from 15,307 to 10,921 rows

(10921, 22)

In [26]:
df_merchandise['ProductColor'].value_counts().head(20)

None        14779
White          53
Brown          44
Black          29
Ivory          25
Flint          22
Driftwoo       19
Silver         17
Linen          13
Sapphire       12
Wheat          12
Seaglass       12
Gold           11
Blue           11
Red            10
Gray            9
Wood            9
Teal            9
Navy            8
Multi           8
Name: ProductColor, dtype: int64

Since there's only 528 entires where the Product Color is any description other than "None", I will remove this column from the dataset as it will not be useful for analysis. 

In [27]:
df_merchandise = df_merchandise.drop(['ProductColor'], axis=1)

In [28]:
df_merchandise['ProductSize'].value_counts().head(20)

None          14798
Jubilee          94
Park Avenu       39
Queen            18
Small            18
Medium           17
King             14
Large            13
Pomeroy          11
53006225         10
CM4550            8
B446              8
CM1700            8
CM3500            8
53005996          7
CM3200            7
9ft X 4ft         6
Wood              6
22x22             5
53005413el        3
Name: ProductSize, dtype: int64

Only 509 of the rows contain useful information regarding Product Size (other than 'None), will drop this column

In [29]:
df_merchandise = df_merchandise.drop(['ProductSize'], axis=1)

In [30]:
df_merchandise['ProductDescription'].value_counts().head(20)

Pillow          611
Lamp            436
Picture         347
Art             315
Chair           296
Rug             228
Mirror          216
Vase            203
Decor           202
Chandelier      145
Barstool        108
Free             98
Sofa             95
Book             88
Desk             87
Nightstand       78
Sidetable        69
Plate            68
Finial           65
Office Chair     65
Name: ProductDescription, dtype: int64

In [31]:
#How many rows are there with a Product Description label that occurs less than 65 times (outside of top20 values)
df_merchandise[df_merchandise.groupby('ProductDescription')['ProductDescription'].transform('size') < 65].shape

(11487, 20)

There are too many rows to go through and clean for Product Description given the timeframe of this report. However, there are rows in which the value for 'ProductType' contains 'None', but has a relevant value for 'ProductDescription' that could replace the 'None' value. This will also be done for rows in which ProductType = 'Accessory' and ProductDescription = other categories already established in ProductType such as 'Table','Chair', etc.

## Need to clean ProductType column to narrow down the different values


In [32]:
accessories = df_merchandise[df_merchandise.ProductType == 'Accessory']
accessories.ProductDescription.value_counts().head(15)

Pillow             313
Lamp               269
Picture            226
Art                220
Vase               142
Mirror             129
Decor              118
Rug                 80
Free                72
Chandelier          72
Pewter Figurine     53
Plate               46
Painting            39
Book                37
Finial              36
Name: ProductDescription, dtype: int64

In [33]:
df_merchandise[df_merchandise.ProductType == 'Pillow'].shape

(371, 20)

In [34]:
df_merchandise[df_merchandise.ProductType == 'Lamp'].shape

(224, 20)

In [35]:
df_merchandise[df_merchandise.ProductType == 'Picture'].shape

(221, 20)

In [36]:
df_merchandise[df_merchandise.ProductType == 'Art'].shape

(365, 20)

In [37]:
df_merchandise[df_merchandise.ProductType == 'Vase'].shape

(45, 20)

In [38]:
df_merchandise[df_merchandise.ProductType == 'Mirror'].shape

(113, 20)

In [39]:
df_merchandise[df_merchandise.ProductType == 'Rug'].shape

(293, 20)

In [40]:
df_merchandise[df_merchandise.ProductType == 'Painting'].shape

(13, 20)

In [41]:
# Add filter to main replacement cell below
table = df_merchandise[df_merchandise.ProductType.str.contains('table', case=False)]
table.ProductType.value_counts()

Table              402
End Table          228
Coffee Table       111
Dining Table       104
Sidetable           79
Side Table          48
Endtable            44
Sofatable           38
Coffeetable         29
Diningtable         23
Sofa Table          17
Table Set            8
Round Table          8
Nesting Tables       6
Diningtable Set      5
Coffetable           4
Entry Table          4
Table/6 Chairs       4
Pub Table            3
Diningtable W/8      3
Table Lamp           3
Table 8 Chairs       3
Table 6 Chairs       3
Table 4 Chairs       3
Cocktail Table       3
Dining Table W/      3
Glass Table          2
Round Sidetable      2
Accent Table         2
Glass Endtable       2
                  ... 
Red Table            1
COFFEE TABLE         1
Child Table/cha      1
Table W/chairs       1
Pubtable             1
Gametable Set        1
Dining Table/ C      1
Glass Top Table      1
Table And CHair      1
Demi Lune Table      1
Table 6/ Chairs      1
CART TABLE           1
Bisrto Tabl

In [42]:
# Add filter to main replacement cell below
chairs = df_merchandise[df_merchandise.ProductType.str.contains('chair', case=False)]
chairs.ProductType.value_counts()

Chair              1194
Chairs               34
Dining Chair         12
Chair/ottoman        10
Chair W/ottoman       7
Dinning Chair         6
Chair And Ottom       6
Chair W/ott           6
Table/6 Chairs        4
Desk Chair            4
Office Chair          4
COPPER CHAIR          4
Barrel Chair          4
Rocking Chair         4
Metal Chair           4
6 Chairs              3
Table 4 Chairs        3
Table 6 Chairs        3
Table 8 Chairs        3
4 Chairs              3
DINING CHAIR          3
Kai Side Chair        3
Swivel Chair          2
Arm Chair             2
Folding Chair         2
Henredon Chair        2
Caracole Chair        2
Dining Chairs/6       2
Side Chair            2
Chairs W/ Green       2
                   ... 
French Chair          1
Table/4 Chairs        1
Set Of 4 Chairs       1
Chair W/green S       1
Table 6/ Chairs       1
Chairs/table          1
Table 7/chairs        1
Zimmerman Chair       1
Chairs Set 4          1
Chair W/ Ott          1
Table And CHair 

In [43]:
accessories.ProductDescription.value_counts().head(15)

Pillow             313
Lamp               269
Picture            226
Art                220
Vase               142
Mirror             129
Decor              118
Rug                 80
Free                72
Chandelier          72
Pewter Figurine     53
Plate               46
Painting            39
Book                37
Finial              36
Name: ProductDescription, dtype: int64

In [44]:
df_merchandise.ProductType.value_counts().head(10)

Accessory    5266
Chair        1194
Decor         655
Table         402
None          384
Pillow        371
Art           365
Sofa          296
Rug           293
End Table     228
Name: ProductType, dtype: int64

In [45]:
# Replace ProductType values for 'Accessory' that also contain top 20 values of ProductType for the ProductDescription category
# Replace values for 'Pillow'
pillow_filter = (df_merchandise['ProductType'] == 'Accessory') & (df_merchandise['ProductDescription'] == 'Pillow')
df_merchandise.loc[pillow_filter, 'ProductType'] = df_merchandise['ProductDescription']

In [46]:
# Ensure new values were correctly added to 'Pillow' value counts and deducted from 'Accessory'
# 'Pillow' should increase from 371 to 684
df_merchandise.ProductType.value_counts().head()

Accessory    4953
Chair        1194
Pillow        684
Decor         655
Table         402
Name: ProductType, dtype: int64

In [47]:
# Ensure this swap did not affect ProductDescription value counts for 'Pillow'
accessories.ProductDescription.value_counts().head()

Pillow     313
Lamp       269
Picture    226
Art        220
Vase       142
Name: ProductDescription, dtype: int64

In [48]:
# Repeat for chairs
chairs = df_merchandise[(df_merchandise['ProductType'] == 'Accessory') & (df_merchandise['ProductDescription'] == 'Chair')]
chairs.shape

(10, 20)

In [49]:
# Repeat for chairs
chair_filter = (df_merchandise['ProductType'] == 'Accessory') & (df_merchandise['ProductDescription'] == 'Chair')
df_merchandise.loc[chair_filter, 'ProductType'] = df_merchandise['ProductDescription']

In [50]:
# Ensure new values were correctly added to 'Pillow' value counts and deducted from 'Accessory'
# 'Chair' value should increase from 1194 to 1204
df_merchandise.ProductType.value_counts().head(10)

Accessory    4943
Chair        1204
Pillow        684
Decor         655
Table         402
None          384
Art           365
Sofa          296
Rug           293
End Table     228
Name: ProductType, dtype: int64

Repeat replacement process for other ProductType categories to better distribute values from **both** 'Accessory' and 'None' in ProductTypw that would better fit into other categories.

In [51]:
# Replace values where 'lamp' occurs
lamp_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('lamp', case=False))
df_merchandise.loc[lamp_filter, 'ProductType'] = 'Lamp'

# Repeat for chairs
# Replace values where 'chair' occurs
chair_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('chair', case=False))
df_merchandise.loc[chair_filter, 'ProductType'] = 'Chairs'

# Repeat for pillows where 'pillow' occurs
pillow_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('pillow', case=False))
df_merchandise.loc[pillow_filter, 'ProductType'] = 'Pillow'

# Repeat for tables
table_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & ((df_merchandise['ProductDescription'].str.contains('table', case=False)) & ~(df_merchandise['ProductDescription'].str.contains('unforgettable', case=False)))
df_merchandise.loc[table_filter, 'ProductType'] = 'Table'

# Repeat for art
art_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('art', case=False))
df_merchandise.loc[art_filter, 'ProductType'] = 'Art'

# Repeat for sofa
sofa_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('sofa', case=False))
df_merchandise.loc[sofa_filter, 'ProductType'] = 'Sofa'

# Repeat for rug
rug_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('rug', case=False))
df_merchandise.loc[rug_filter, 'ProductType'] = 'Rug'

# Repeat for pictures as 'Art'
picture_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('picture', case=False))
df_merchandise.loc[picture_filter, 'ProductType'] = 'Art'

# Repeat for desk
desk_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('desk', case=False))
df_merchandise.loc[desk_filter, 'ProductType'] = 'Desk'

# Repeat for bed
bed_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('bed', case=False))
df_merchandise.loc[bed_filter, 'ProductType'] = 'Bed'

# Repeat for chest
chest_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('chest', case=False))
df_merchandise.loc[chest_filter, 'ProductType'] = 'Chest'

# Repeat for mirror
mirror_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('mirror', case=False))
df_merchandise.loc[mirror_filter, 'ProductType'] = 'Mirror'

# Repeat for painting as 'Art'
painting_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (df_merchandise['ProductDescription'].str.contains('painting', case=False))
df_merchandise.loc[painting_filter, 'ProductType'] = 'Art'

# Repeat for light
light_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & ((df_merchandise['ProductDescription'].str.contains('light', case=False)) & ~(df_merchandise['ProductDescription'].str.contains('sconce', case=False)))
df_merchandise.loc[light_filter, 'ProductType'] = 'Light'

# Repeat for chandelier, lantern as 'Lighting'
chandelier_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (((df_merchandise['ProductDescription'].str.contains('chandelier', case=False)))
                                                                      | ((df_merchandise['ProductDescription'].str.contains('lantern', case=False))))
df_merchandise.loc[chandelier_filter, 'ProductType'] = 'Lighting'

# Repeat for clock, vase, book, pewter items, bowl, greenery, tray, cross, urn, plate, decor as 'Decor'
decor_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & (((df_merchandise['ProductDescription'].str.contains('decor', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('clock', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('book', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('pewter', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('bowl', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('greenery', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('tray', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('cross', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('urn', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('plate', case=False)))
                                                                | ((df_merchandise['ProductDescription'].str.contains('vase', case=False))))
df_merchandise.loc[decor_filter, 'ProductType'] = 'Decor'

# Repeat for free
free_filter = ((df_merchandise['ProductType'] == 'Accessory') | (df_merchandise['ProductType'] == 'None')) & ((df_merchandise['ProductDescription'].str.contains('free', case=False)))
df_merchandise.loc[free_filter, 'ProductType'] = 'Free'

# Repeat for lamp, light as 'Lighting' to consolidate
lighting_filter = (df_merchandise['ProductType'] == 'Lamp') | (df_merchandise['ProductType'] == 'Light')
df_merchandise.loc[lighting_filter, 'ProductType'] = 'Lighting'

# Repeat for Chandelier as 'Lighting' to consolidate
pt_chandelier_filter = (df_merchandise['ProductType'] == 'Chandelier')
df_merchandise.loc[pt_chandelier_filter, 'ProductType'] = 'Lighting'

# Repeat for sleeper as 'Sofa'
none_sleeper_filter = (df_merchandise['ProductType'] == 'None') & ((df_merchandise['ProductDescription'].str.contains('sleeper', case=False)))
df_merchandise.loc[none_sleeper_filter, 'ProductType'] = 'Sofa'

# Repeat for hardware, finials, rods as 'Accessory'
none_hw_filter = (df_merchandise['ProductType'] == 'None') & ((df_merchandise['ProductDescription'].str.contains('hardware', case=False))
                                                             |(df_merchandise['ProductDescription'].str.contains('finial', case=False))
                                                             |(df_merchandise['ProductDescription'].str.contains('rod', case=False)))
df_merchandise.loc[none_hw_filter, 'ProductType'] = 'Accessory'

# Repeat for all values of 'bed' into 'Bed' category
all_bed_filter = df_merchandise.ProductType.str.contains('bed', case=False)
df_merchandise.loc[all_bed_filter, 'ProductType'] = 'Bed'

# Repeat for all values of 'chair','barstool' into 'Chair' category in PT to consolidate
# contains 'dining chairs', 'sofa chair', 'side chair', etc.
mass_chair_filter = (df_merchandise.ProductType.str.contains('chair', case=False)) | (df_merchandise.ProductType.str.contains('barstool', case=False))
df_merchandise.loc[mass_chair_filter, 'ProductType'] = 'Chairs'

df_merchandise.ProductType.value_counts().head(25)

Accessory       2202
Decor           1622
Chairs          1596
Lighting        1132
Art             1076
Pillow           792
Rug              473
Table            454
Mirror           303
Sofa             303
Bed              278
End Table        228
Picture          221
Desk             175
None             150
Coffee Table     111
Chest            109
Dining Table     104
Console           99
Free              98
Ottoman           93
Cabinet           90
Book              86
Sidetable         79
Bench             65
Name: ProductType, dtype: int64